export const steps: any = [
  {
    tour: "welcome",
    steps: [
      {
        icon: <>👋</>,
        title: "Welcome to Tournament-Pool!",
        content: <>This is step 1</>,
        selector: "#welcome-step1",
        side: "bottom",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 12,
      },
      {
        icon: <>🪄</>,
        title: "It's like magic!",
        content: <>This is step 2</>,
        selector: "#welcome-step2",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 12,
      },
      {
        icon: <>🎈</>,
        title: "Party time!",
        content: <>This is step 4</>,
        selector: "#welcome-step4",
        side: "top",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
    ],
  },
  {
    tour: "first-tournament",
    steps: [
      {
        icon: <>🌟</>,
        title: "Welcome to Tour 2!",
        content: <>This is step 1 of Tour 2</>,
        selector: "#tour2-step1",
        side: "top",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🔥</>,
        title: "Feel the heat!",
        content: <>This is step 2 of Tour 2</>,
        selector: "#tour2-step2",
        side: "top",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 999,
      },
      {
        icon: <>🎈</>,
        title: "Party time!",
        content: <>This is step 3 of Tour 2</>,
        selector: "#tour2-step3",
        side: "top",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
        nextRoute: "/page-two",
      },
      {
        icon: <>🎉</>,
        title: "Celebrate!",
        content: <>This is step 4 of Tour 2</>,
        selector: "#tour2-step4",
        side: "top",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
        prevRoute: "/",
      },
    ],
  },
];
